[package]
name = "enderpack"
version = "0.1.0"
edition = "2024"

[dependencies]
enderpack_macro = { path = "./enderpack_macro" }
case = "1.0.0"
derive-new = "0.7.0"
serde = "1.0.219"
serde_json = "1.0.140"
strum = { version = "0.27.1", features = ["derive"] }
uuid = "1.17.0"
